### ISSUE TITLE
Verify error is constant as number of workers varies

### ISSUE THREAD

**Issue by stsievert** [epfml/powersgd#2]
To me, the most interesting part of this code is the all-reduce scheme with error correction. It appears the error will be constant as the number of workers varies from the (brief) description of error correction on the NeurIPS poster.

**Comment by tvogels** [comment]
This is correct. As long as yo use a constant batch size, it doesn’t matter how this batch is divided over workers. 

Note that batch norm breaks this property as it breaks the independence between examples in a mini batch. So it would be best to try this with VGG w/o batch norm rather than with a ResNet. It might also be a little tricky to get the shuffling consistent.

**Comment by stsievert** [comment]
I've thought some more about the figures I'd like to see on the poster (which is related to this issue but largely tangential).

Specifically, I'd like to see a figure comparing gradient compression error as the number of workers scale for PowerSGD *and competing methods*. It will vary for QSGD/Terngrad but will be constant for PowerSGD. This will depend on the bits communicated, so my first thought would be to fix the bits communicated at N MB.
