### ISSUE TITLE
An error-feedback issue.

### ISSUE THREAD

**Issue by anxuthu** [epfml/powersgd#3]
Hi,

Is "memory_out" for the error-feedback in class RankKReducer of gradient_reducers.py?
```def reduce(self, grad_in, grad_out, memory_out):```

It seems that the local error is computed here:
```
with self.timer("reduce.outerprod", verbosity=2):
    for p, q, (tensor, out, mem) in zip(ps, qs, high_rank_tensors):
        # Set the output gradient
        torch.matmul(p, q.t(), out=out.data[:])
        mem.data[:] = tensor - out
```

However, I think the local compressed gradient rather than the averaged version should be subtracted from the local gradient. That is, remove the last line in the codes above and change

```
with self.timer("reduce.compute.q", verbosity=2):
    for p, q, (tensor, _, _) in zip(ps, qs, high_rank_tensors):
    matrix = tensor.view(tensor.shape[0], -1)
    torch.matmul(matrix.t(), p, out=q)
```

to

```
with self.timer("reduce.compute.q", verbosity=2):
    for p, q, (tensor, _, mem) in zip(ps, qs, high_rank_tensors):
        matrix = tensor.view(tensor.shape[0], -1)
        torch.matmul(matrix.t(), p, out=q)
        mem.data[:] = tensor - torch.matmul(p, q.t()).view_as(tensor)
```

Is that correct?

Besides, the input and kernel dimensions of the 4d gradient in the convolutional layers should be flattened. Are there such computations in this repository? I tried but couldn't find them.

Thanks

**Comment by tvogels** [comment]
Hi, thanks for your message!
This is a good question. The code is indeed different from the algorithm described in the paper, but the two versions are algorithmically equivalent. To see this, consider that the algorithm is only a function of the 'average' memory across worker, rather than of the worker-specific values. So it doesn't matter which worker stores what, as long as their average is correct. The difference between the two code snippets you sent cancel out when summed across workers. Let me know if I should write a more mathematical explanation.

About the flattening operations, they are in lines like this:
```matrix = tensor.view(tensor.shape[0], -1)```
`tensor.shape[0]` includes the 'output' dimension and `-1` flattens the input and kernel dimensions.

Hope this helps.

**Comment by anxuthu** [comment]
Hi, thanks for your response!

About the flattening operations, a typical shape of the convolutional layers in ResNet-110 can be [64,64,3,3]. Maybe it will be more efficient to flatten it to [64x3,64x3] than [64,64x3x3].

The mathematical explanation of why local compressed gradient is used for computing local errors in current works can be found in Lemma 6 of "Communication-Efficient Distributed Blockwise Momentum SGD with Error-Feedback". Maybe we can also bound them when using averaged compressed gradient to compute local errors, but I have not come across such literature. Besides, I am exploring some ideas based on PowerSGD and found that using averaged version may empirically lead to poor convergence (there could be some errors in my codes, or the different problem settings enlarges this difference).

**Comment by tvogels** [comment]
> About the flattening operations, a typical shape of the convolutional layers in ResNet-110 can be [64,64,3,3]. Maybe it will be more efficient to flatten it to [64x3,64x3] than [64,64x3x3].

The reasoning behind going for [64, 64x3x3] is the natural separation between 'inputs' and 'outputs' of the layer. The convolution applies the same linear transformation to each 64x3x3 slice of inputs to produce 64 outputs. That said, 64x3, 64x3 could indeed yield higher compression, and it might work fine as well.

> Besides, I am exploring some ideas based on PowerSGD and found that using averaged version may empirically lead to poor convergence.
This is surprising to me. I expect them to perform exactly the same (in the case of PowerSGD), up to potential numerical stability issues. If you make changes to the algorithm that break the equivalence, the local values should be used.

In the code snippets you included, workers all use the same value for `p`, and have different `q`'s. Due to linearity
```
average_i(tensor[worker i] - p q[worker i]^T) == average_i(tensor[worker i] - p average_i(q[worker i])^T)
```
And because the next PowerSGD step only depends on the average memory (through linear operations), the next step will be the same irrespective of which option you choose. We choose the one in code because it avoids some unnecessary computation.

**Comment by anxuthu** [comment]
Thank you!
